name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  onesignal_flutter: ^5.1.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Comment out flutter_native_splash temporarily
# flutter_native_splash: 
#   android: true
#   ios: true
#   color: "#D64151"
#   image: assets/images/splash_logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.jpg"
  adaptive_icon_background: "#D64151"
  adaptive_icon_foreground: "assets/images/splash_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/